name: Validate merge requests

on:
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    validate:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - uses: ./.github/actions/setup
            - uses: ./.github/actions/build
            - uses: ./.github/actions/lint
            - uses: ./.github/actions/test
            - uses: ./.github/actions/e2e-local